cons = ({'type': 'ineq', 'fun': lambda x: x[0] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[0] + 10},
        {'type': 'ineq', 'fun': lambda x: x[1] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[1] + 10},
        {'type': 'ineq', 'fun': lambda x: x[2] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[2] + 500},
        {'type': 'ineq', 'fun': lambda x: x[3] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[3] + 100},
        {'type': 'ineq', 'fun': lambda x: x[4] - (-10)},
        {'type': 'ineq', 'fun': lambda x: -x[4] + 10},

        {'type': 'ineq', 'fun': lambda x: x[5] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[5] + 10},
        {'type': 'ineq', 'fun': lambda x: x[6] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[6] + 10},
        {'type': 'ineq', 'fun': lambda x: x[7] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[7] + 500},
        {'type': 'ineq', 'fun': lambda x: x[8] - 0},
        {'type': 'ineq', 'fun': lambda x: -x[8] + 100},
        {'type': 'ineq', 'fun': lambda x: x[9] - (-10)},
        {'type': 'ineq', 'fun': lambda x: -x[9] + 10}
        )